"""Add inductor

Revision ID: 0ad54fb43dd5
Revises: a2e2efe545fd
Create Date: 2024-07-10 17:23:21.012278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad54fb43dd5'
down_revision: Union[str, None] = 'a2e2efe545fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inductor',
    sa.Column('inductance_henries_min', sa.Float(), nullable=True),
    sa.Column('inductance_henries_max', sa.Float(), nullable=True),
    sa.Column('dc_resistance_min', sa.Float(), nullable=True),
    sa.Column('dc_resistance_max', sa.Float(), nullable=True),
    sa.Column('operating_current_amps_min', sa.Float(), nullable=True),
    sa.Column('operating_current_amps_max', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_min', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_max', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('overhead_cost', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('lcsc_id', sa.String(), nullable=True),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('footprint_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lcsc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inductor')
    # ### end Alembic commands ###
