"""Add mosfets

Revision ID: 88955c87f972
Revises: 0ad54fb43dd5
Create Date: 2024-07-11 14:44:09.309268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88955c87f972'
down_revision: Union[str, None] = '0ad54fb43dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mosfet',
    sa.Column('operating_voltage_volts_min', sa.Float(), nullable=True),
    sa.Column('operating_voltage_volts_max', sa.Float(), nullable=True),
    sa.Column('operating_current_amps_min', sa.Float(), nullable=True),
    sa.Column('operating_current_amps_max', sa.Float(), nullable=True),
    sa.Column('operating_power_watts_min', sa.Float(), nullable=True),
    sa.Column('operating_power_watts_max', sa.Float(), nullable=True),
    sa.Column('gate_voltage_volts_min', sa.Float(), nullable=True),
    sa.Column('gate_voltage_volts_max', sa.Float(), nullable=True),
    sa.Column('on_resistance_ohms_min', sa.Float(), nullable=True),
    sa.Column('on_resistance_ohms_max', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_min', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_max', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('overhead_cost', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('lcsc_id', sa.String(), nullable=True),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('footprint_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lcsc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mosfet')
    # ### end Alembic commands ###
