"""Add range for power and voltage ratings

Revision ID: a2e2efe545fd
Revises: c041226a1f05
Create Date: 2024-07-10 15:44:03.676990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e2efe545fd'
down_revision: Union[str, None] = 'c041226a1f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacitors', sa.Column('operating_voltage_volts_min', sa.Float(), nullable=True))
    op.add_column('capacitors', sa.Column('operating_voltage_volts_max', sa.Float(), nullable=True))
    op.drop_column('capacitors', 'rated_voltage_volts')
    op.add_column('resistors', sa.Column('operating_power_watts_min', sa.Float(), nullable=True))
    op.add_column('resistors', sa.Column('operating_power_watts_max', sa.Float(), nullable=True))
    op.drop_column('resistors', 'rated_power_watts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resistors', sa.Column('rated_power_watts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('resistors', 'operating_power_watts_max')
    op.drop_column('resistors', 'operating_power_watts_min')
    op.add_column('capacitors', sa.Column('rated_voltage_volts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('capacitors', 'operating_voltage_volts_max')
    op.drop_column('capacitors', 'operating_voltage_volts_min')
    # ### end Alembic commands ###
