"""Initial commit

Revision ID: c041226a1f05
Revises: 
Create Date: 2024-07-10 10:16:28.718282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c041226a1f05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacitors',
    sa.Column('capacitance_farads_min', sa.Float(), nullable=True),
    sa.Column('capacitance_farads_max', sa.Float(), nullable=True),
    sa.Column('rated_voltage_volts', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_min', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_max', sa.Float(), nullable=True),
    sa.Column('dielectric_code', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('overhead_cost', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('lcsc_id', sa.String(), nullable=True),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('footprint_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lcsc_id')
    )
    op.create_table('resistors',
    sa.Column('resistance_ohms_min', sa.Float(), nullable=True),
    sa.Column('resistance_ohms_max', sa.Float(), nullable=True),
    sa.Column('rated_power_watts', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_min', sa.Float(), nullable=True),
    sa.Column('operating_temp_celsius_max', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('overhead_cost', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('lcsc_id', sa.String(), nullable=True),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('footprint_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lcsc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resistors')
    op.drop_table('capacitors')
    # ### end Alembic commands ###
